apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-messenger
  namespace: messenger
spec:
  containers:
  - name: dnsutils
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
