apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: messenger
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: messenger
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notification-service
        app.kubernetes.io/component: microservice
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: notification-service
        image: messenger/notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: messenger-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: messenger-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: messenger-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: DB_PASS
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: messenger-config
              key: AUTH_SERVICE_URL
        - name: VAPID_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: VAPID_PUBLIC_KEY
        - name: VAPID_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: VAPID_PRIVATE_KEY
        - name: VAPID_SUBJECT
          valueFrom:
            configMapKeyRef:
              name: messenger-config
              key: VAPID_SUBJECT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1001
